version: "3"
services:
  db:
    image: postgres:12.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fastcampus
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgres-data: